-- \i C:/Users/victor.dahl/Documents/GitHub/paca/app/psql/fill_db.sql
\set ON_ERROR_STOP ON

INSERT INTO person (anstid, name, email, supervisor)VALUES('1', 'Alice Andersson', 'alice.andersson@paca.com', 't');
INSERT INTO person (anstid, name, email, supervisor)VALUES('2', 'Alicia Johansson', 'alicia.johansson@paca.com', 't');
INSERT INTO person (anstid, name, email, supervisor)VALUES('3', 'Olivia Karlsson', 'olivia.karlsson@paca.com', 't');
INSERT INTO person (anstid, name, email, supervisor)VALUES('4', 'Ella Nilsson', 'ella.nilsson@paca.com', 't');
INSERT INTO person (anstid, name, email, supervisor)VALUES('5', 'Ebba Eriksson', 'ebba.eriksson@paca.com', 't');
INSERT INTO person (anstid, name, email, supervisor)VALUES('6', 'Lilly Larsson', 'lilly.larsson@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('7', 'Astrid Olsson', 'astrid.olsson@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('8', 'Saga Persson', 'saga.persson@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('9', 'Freja Svensson', 'freja.svensson@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('10', 'Wilma Gustafsson', 'wilma.gustafsson@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('11', 'Maja Pettersson', 'maja.pettersson@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('12', 'Agnes Jonsson', 'agnes.jonsson@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('13', 'Elsa Jansson', 'elsa.jansson@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('14', 'Alma Hansson', 'alma.hansson@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('15', 'Clara Bengtsson', 'clara.bengtsson@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('16', 'Ellie Jönsson', 'ellie.jönsson@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('17', 'Selma Lindberg', 'selma.lindberg@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('18', 'Julia Jakobsson', 'julia.jakobsson@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('19', 'Stella Magnusson', 'stella.magnusson@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('20', 'Alva Olofsson', 'alva.olofsson@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('21', 'Signe Lindström', 'signe.lindström@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('22', 'Vera Lindqvist', 'vera.lindqvist@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('23', 'Ellen Lindgren', 'ellen.lindgren@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('24', 'Leah Axelsson', 'leah.axelsson@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('25', 'Molly Berg', 'molly.berg@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('26', 'Ines Bergström', 'ines.bergström@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('27', 'Ester Lundberg', 'ester.lundberg@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('28', 'Linnea Lundgren', 'linnea.lundgren@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('29', 'Isabelle Lind', 'isabelle.lind@paca.com', 'f');
INSERT INTO person (anstid, name, email, supervisor)VALUES('30', 'Sara Lundqvist', 'sara.lundqvist@paca.com', 'f');

INSERT INTO phone (anstid_f, phone_nr) VALUES('1', '0761111111');
INSERT INTO phone (anstid_f, phone_nr) VALUES('2', '0761111112');
INSERT INTO phone (anstid_f, phone_nr) VALUES('3', '0761111113');
INSERT INTO phone (anstid_f, phone_nr) VALUES('4', '0761111114');
INSERT INTO phone (anstid_f, phone_nr) VALUES('5', '0761111115');
INSERT INTO phone (anstid_f, phone_nr) VALUES('6', '0761111116');
INSERT INTO phone (anstid_f, phone_nr) VALUES('7', '0761111117');
INSERT INTO phone (anstid_f, phone_nr) VALUES('8', '0761111118');
INSERT INTO phone (anstid_f, phone_nr) VALUES('9', '0761111119');
INSERT INTO phone (anstid_f, phone_nr) VALUES('10', '0761111120');
INSERT INTO phone (anstid_f, phone_nr) VALUES('11', '0761111121');
INSERT INTO phone (anstid_f, phone_nr) VALUES('12', '0761111122');
INSERT INTO phone (anstid_f, phone_nr) VALUES('13', '0761111123');
INSERT INTO phone (anstid_f, phone_nr) VALUES('14', '0761111124');
INSERT INTO phone (anstid_f, phone_nr) VALUES('15', '0761111125');
INSERT INTO phone (anstid_f, phone_nr) VALUES('16', '0761111126');
INSERT INTO phone (anstid_f, phone_nr) VALUES('17', '0761111127');
INSERT INTO phone (anstid_f, phone_nr) VALUES('18', '0761111128');
INSERT INTO phone (anstid_f, phone_nr) VALUES('19', '0761111129');
INSERT INTO phone (anstid_f, phone_nr) VALUES('20', '0761111130');
INSERT INTO phone (anstid_f, phone_nr) VALUES('21', '0761111131');
INSERT INTO phone (anstid_f, phone_nr) VALUES('22', '0761111132');
INSERT INTO phone (anstid_f, phone_nr) VALUES('23', '0761111133');
INSERT INTO phone (anstid_f, phone_nr) VALUES('24', '0761111134');
INSERT INTO phone (anstid_f, phone_nr) VALUES('25', '0761111135');
INSERT INTO phone (anstid_f, phone_nr) VALUES('26', '0761111136');
INSERT INTO phone (anstid_f, phone_nr) VALUES('27', '0761111137');
INSERT INTO phone (anstid_f, phone_nr) VALUES('28', '0761111138');
INSERT INTO phone (anstid_f, phone_nr) VALUES('29', '0761111139');

INSERT INTO pass (pass_id, name, behov, date, time, break) VALUES('1', 'chef', '1', '2018-03-22', '08:00', '00:45');
INSERT INTO pass (pass_id, name, behov, date, time, break) VALUES('2', 'kassa', '1', '2018-03-22', '08:00', '00:45');
INSERT INTO pass (pass_id, name, behov, date, time, break) VALUES('3', 'kassa', '1', '2018-03-22', '08:00', '00:45');
INSERT INTO pass (pass_id, name, behov, date, time, break) VALUES('4', 'kassa', '1', '2018-03-22', '08:00', '00:45');
INSERT INTO pass (pass_id, name, behov, date, time, break) VALUES('5', 'kassa', '1', '2018-03-22', '08:00', '00:45');
INSERT INTO pass (pass_id, name, behov, date, time, break) VALUES('6', 'lager', '2', '2018-03-22', '08:00', '00:45');
INSERT INTO pass (pass_id, name, behov, date, time, break) VALUES('7', 'lager', '2', '2018-03-22', '08:00', '00:45');
INSERT INTO pass (pass_id, name, behov, date, time, break) VALUES('8', 'butik', '2', '2018-03-22', '08:00', '00:45');
INSERT INTO pass (pass_id, name, behov, date, time, break) VALUES('9', 'butik', '2', '2018-03-22', '08:00', '00:45');
INSERT INTO pass (pass_id, name, behov, date, time, break) VALUES('10', 'städ', '2', '2018-03-22', '08:00', '00:45');

INSERT INTO shift_demand (pass_id_f, pid_f) VALUES('1', '1');
INSERT INTO shift_demand (pass_id_f, pid_f) VALUES('2', '2');
INSERT INTO shift_demand (pass_id_f, pid_f) VALUES('3', '3');
INSERT INTO shift_demand (pass_id_f, pid_f) VALUES('4', '4');
INSERT INTO shift_demand (pass_id_f, pid_f) VALUES('5', '5');
INSERT INTO shift_demand (pass_id_f, pid_f) VALUES('6', '6');
INSERT INTO shift_demand (pass_id_f, pid_f) VALUES('7', '7');
INSERT INTO shift_demand (pass_id_f, pid_f) VALUES('8', '8');
INSERT INTO shift_demand (pass_id_f, pid_f) VALUES('9', '9');
INSERT INTO shift_demand (pass_id_f, pid_f) VALUES('10', '10');

INSERT INTO availability (anstid_f, date, time, comment) VALUES('1', '2018-03-22', '08:00', 'Kan jobba 8 h');
INSERT INTO availability (anstid_f, date, time, comment) VALUES('2', '2018-03-22', '08:00', 'Kan jobba 8 h');
INSERT INTO availability (anstid_f, date, time, comment) VALUES('3', '2018-03-22', '08:00', 'Kan jobba 8 h');
INSERT INTO availability (anstid_f, date, time, comment) VALUES('4', '2018-03-22', '08:00', 'Kan jobba 8 h');
INSERT INTO availability (anstid_f, date, time, comment) VALUES('5', '2018-03-22', '08:00', 'Kan jobba 8 h');
INSERT INTO availability (anstid_f, date, time, comment) VALUES('6', '2018-03-22', '08:00', 'Kan jobba 8 h');
INSERT INTO availability (anstid_f, date, time, comment) VALUES('7', '2018-03-22', '08:00', 'Kan jobba 8 h');
INSERT INTO availability (anstid_f, date, time, comment) VALUES('8', '2018-03-22', '08:00', 'Kan jobba 8 h');
INSERT INTO availability (anstid_f, date, time, comment) VALUES('9', '2018-03-22', '08:00', 'Kan jobba 8 h');
INSERT INTO availability (anstid_f, date, time, comment) VALUES('10', '2018-03-22', '08:00', 'Kan jobba 8 h');

INSERT INTO department (depid, name, boss) VALUES('1', 'admin', '1');
INSERT INTO department (depid, name, boss) VALUES('2', 'kassa', '1');
INSERT INTO department (depid, name, boss) VALUES('3', 'lager', '1');
INSERT INTO department (depid, name, boss) VALUES('4', 'butik', '1');

INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('1', '1');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('2', '2');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('3', '3');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('4', '4');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('5', '1');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('6', '2');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('7', '3');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('8', '4');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('9', '1');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('10', '2');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('11', '3');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('12', '4');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('13', '1');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('14', '2');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('15', '3');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('16', '4');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('17', '1');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('18', '2');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('19', '3');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('20', '4');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('21', '1');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('22', '2');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('23', '3');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('24', '4');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('25', '1');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('26', '2');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('27', '3');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('28', '4');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('29', '1');
INSERT INTO avd_anstid (anstid_f, depid_f)  VALUES('30', '2');

