# Generated by Django 2.0.4 on 2018-05-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'användare', 'verbose_name_plural': 'användare'},
        ),
        migrations.AlterModelOptions(
            name='emergencycontacts',
            options={'verbose_name': 'anhörig', 'verbose_name_plural': 'närmaste anhöriga'},
        ),
    ]
