# Generated by Django 2.0.4 on 2018-04-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ort'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='empid',
            field=models.IntegerField(default=0, unique=True, verbose_name='Anställnings-ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(blank=True, default=0, max_length=20, verbose_name='Telefonnummer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='pnr',
            field=models.IntegerField(default=0, max_length=12, unique=True, verbose_name='Personnummer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='postcode',
            field=models.CharField(blank=True, max_length=5, verbose_name='Postnummer'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street',
            field=models.CharField(blank=True, max_length=100, verbose_name='Gatunamn och -nummer'),
        ),
    ]
