# Generated by Django 2.0.4 on 2018-05-20 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20180518_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Namn')),
                ('relationship', models.CharField(max_length=50, verbose_name='Relation')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefonnummer')),
                ('user_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
