# Generated by Django 2.0.4 on 2018-05-03 11:15

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20180501_1026'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='pnr',
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of User'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='emp_type',
            field=models.CharField(choices=[('full time', 'Heltid'), ('part time', 'Deltid'), ('hourly paid', 'Timanställning'), ('probationary', 'Provanställning')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='empid',
            field=models.CharField(max_length=20, unique=True, verbose_name='Anställnings-ID'),
        ),
    ]
