# Generated by Django 2.0.4 on 2018-04-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_auto_20180427_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='empid',
            field=models.IntegerField(verbose_name='Anställnings-ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pnr',
            field=models.IntegerField(max_length=12, verbose_name='Personnummer'),
        ),
    ]
