# Generated by Django 2.0.4 on 2018-05-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20180523_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'nyhet', 'verbose_name_plural': 'nyheter'},
        ),
    ]
