# Generated by Django 2.0.4 on 2018-05-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='req_usr',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
