# Generated by Django 2.0.4 on 2018-05-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='namn'),
        ),
    ]
