# Generated by Django 2.0.4 on 2018-05-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0002_event_req_usr'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='dept',
            field=models.CharField(default='Kassa', max_length=20),
            preserve_default=False,
        ),
    ]
