# Generated by Django 2.0.4 on 2018-05-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0002_event_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'avdelning', 'verbose_name_plural': 'avdelningar'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'pass', 'verbose_name_plural': 'arbetspass'},
        ),
    ]
