# Generated by Django 2.0.4 on 2018-05-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0003_auto_20180523_1753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'pass', 'verbose_name_plural': 'pass'},
        ),
    ]
