# Generated by Django 2.0.4 on 2018-05-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0003_event_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='dept',
        ),
    ]
