# Generated by Django 2.0.4 on 2018-05-23 16:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fullcalendar', '0004_auto_20180523_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete='Ansvarig', to=settings.AUTH_USER_MODEL),
        ),
    ]
