# Generated by Django 2.0.4 on 2018-05-23 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fullcalendar', '0007_auto_20180523_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(default='Beskrivning saknas.', verbose_name='Beskrivning'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Namn'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.ForeignKey(on_delete='Titel', to='fullcalendar.Department'),
        ),
        migrations.AlterField(
            model_name='event',
            name='username',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Bokad på'),
        ),
    ]
